name: Continuous Integration

env:
  GOOGLE_PLACES_KEY: ${{ secrets.GOOGLE_PLACES_KEY }}
  GOOGLE_PLACE_ID: ${{ secrets.GOOGLE_PLACE_ID }}
  INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
  INSTAGRAM_CLIENT_ID: ${{ secrets.INSTAGRAM_CLIENT_ID }}
  INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm audit
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run pretty-quick
      - run: npm run test
      - run: npm run codecov
